set(_CATKIN_CURRENT_PACKAGE "vs_demo_swagat")
set(vs_demo_swagat_VERSION "0.0.0")
set(vs_demo_swagat_MAINTAINER "ur5 <ur5@todo.todo>")
set(vs_demo_swagat_PACKAGE_FORMAT "1")
set(vs_demo_swagat_BUILD_DEPENDS "roscpp" "std_msgs")
set(vs_demo_swagat_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(vs_demo_swagat_BUILDTOOL_DEPENDS "catkin")
set(vs_demo_swagat_BUILDTOOL_EXPORT_DEPENDS )
set(vs_demo_swagat_EXEC_DEPENDS "roscpp" "std_msgs")
set(vs_demo_swagat_RUN_DEPENDS "roscpp" "std_msgs")
set(vs_demo_swagat_TEST_DEPENDS )
set(vs_demo_swagat_DOC_DEPENDS )
set(vs_demo_swagat_DEPRECATED "")